'use client';
import { useState, useEffect, useCallback, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { validateDonation } from '@/lib/influencer-policy.mjs';
type Partner={id:string;code:string;name:string;intro:string;contactEmail:string;status:string;revision:number;referralVisits:number;paidOrders:number;activeSubscriptions:number;donatedCents:number};
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
async function api(path:string,input?:unknown){const r=await fetch('/api/admin/'+path,{method:input===undefined?'GET':'POST',headers:input===undefined?{}:{'Content-Type':'application/json'},body:input===undefined?undefined:JSON.stringify(input),cache:'no-store'});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'Could not complete this request.');return data;}
export default function Influencers({onUpdated}:{onUpdated:()=>Promise<unknown>}){
 const [report,setReport]=useState<{partners:Partner[];transfers:any[]}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[editor,setEditor]=useState<Partner|'new'|null>(null),[selected,setSelected]=useState<Partner|null>(null),[donation,setDonation]=useState(false),[reversal,setReversal]=useState<any>(null),[reason,setReason]=useState(''),[origin,setOrigin]=useState('');
 const refresh=useCallback(async()=>{const r=await api('influencers');setReport(r);},[]);
 useEffect(()=>{setOrigin(window.location.origin);refresh().catch(e=>setError(e.message));},[refresh]);
 async function action(path:string,input:unknown,message:string){setBusy(true);setError('');setNotice('');try{await api(path,input);await refresh();await onUpdated();setNotice(message);return true;}catch(e){setError(e instanceof Error?e.message:'Unable to save.');return false;}finally{setBusy(false);}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Copied.');}catch{setError('Clipboard access is unavailable. Select and copy the text instead.');}}
 const url=(p:Partner)=>`${origin}/creators/${p.code}`;
 const message=selected?`Little treats. Bigger possibilities.\n\nI’m teaming up with Sunnybunch to support Mia’s Place, its planned nonprofit for meaningful employment and lasting opportunity for people with autism and other disabilities. There is no influencer commission. Sunnybunch donates all profits to Mia’s Place.\n\nVisit our community page to see the completed donations attributed to us: ${url(selected)}\n\nOnce checkout opens, use this link before you shop. It selects our community for eligible purchases within 30 days; subscriptions keep their original partner until cancellation. The most recent school or influencer link receives credit, and each purchase counts toward one partner.\n\nLaunch draft: checkout is not yet connected. Public totals reflect completed donations recorded by Sunnybunch after reconciling each community’s share, not sales or estimated profit.`:'';
 return <div className="influencer-admin"><div className="section-top school-admin-top"><div><p className="eyebrow">SUNNYBUNCH × MIA’S PLACE</p><h2>Influencer communities</h2><p>Personal links. Visible impact. A shared purpose, with no commission.</p></div><Button disabled={busy} onClick={()=>setEditor('new')}>Add influencer</Button></div>
 {error&&<p className="message error" role="alert">{error}</p>}{notice&&<p className="message" role="status">{notice}</p>}
 <div className="overview-grid"><section className="panel sunshine"><p className="eyebrow">PUBLIC COMMUNITY TOTALS</p><h2>{report?money(report.partners.reduce((s,p)=>s+p.donatedCents,0)):'—'}</h2><p>Completed donations recorded for influencer communities. Each community’s share appears on its public page.</p><p className="small">Part of Sunnybunch’s existing 100%-of-profits commitment to Mia’s Place.</p></section><section className="panel"><h3>What counts toward impact?</h3><p>A completed donation you have confirmed and reconciled. Record the transfer once, then allocate its shares across communities.</p><p className="small">Sales, subscriptions and automated profit reconciliation still need payment integration. Recording here publishes a total; it does not transfer money.</p><Button variant="outline" disabled={busy||!report?.partners.some(p=>p.status!=='draft')} onClick={()=>{setError('');setDonation(true);}}>Record completed donation</Button></section></div>
 {editor&&<InfluencerEditor key={editor==='new'?'new':editor.id} partner={editor==='new'?null:editor} busy={busy} onCancel={()=>setEditor(null)} onSave={async v=>{if(await action('influencers',v,'Influencer saved. Active profiles have a live referral and impact page.')){setEditor(null);setSelected(null);}}}/>}
 <section className="panel"><h3>Your communities</h3><p className="small">The most recent active school or influencer link receives 30-day credit. Existing subscriptions retain their original partner. Visits include bots and repeat visits.</p>{!report?<p className="empty">Loading communities… <Button variant="outline" onClick={()=>refresh().catch(e=>setError(e.message))}>Retry</Button></p>:!report.partners.length?<div className="empty"><h3>Give your first influencer a place to share.</h3><p>Add their public name, introduction and permanent link code. Their page starts at $0 recorded, with no invented sales or donations.</p><Button onClick={()=>setEditor('new')}>Add first influencer</Button></div>:<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Community</TableHead><TableHead>Status</TableHead><TableHead>Visits</TableHead><TableHead>Paid orders</TableHead><TableHead>Active subscriptions</TableHead><TableHead>Recorded donations</TableHead><TableHead>Manage</TableHead></TableRow></TableHeader><TableBody>{report.partners.map(p=><TableRow key={p.id}><TableCell><strong>{p.name}</strong><span className="school-cell-detail">{p.code}</span></TableCell><TableCell>{p.status}</TableCell><TableCell>{p.referralVisits}</TableCell><TableCell>{p.paidOrders}</TableCell><TableCell>{p.activeSubscriptions}</TableCell><TableCell>{money(p.donatedCents)}</TableCell><TableCell><div className="school-row-actions"><Button variant="outline" onClick={()=>setEditor(p)}>Edit</Button><Button variant="outline" onClick={()=>setSelected(p)}>Share</Button></div></TableCell></TableRow>)}</TableBody></Table></div>}</section>
 {selected&&<section className="panel"><h3>{selected.name}’s sharing kit</h3><p>{selected.status==='active'?'This one link selects the community and displays its recorded donations.':selected.status==='paused'?'The impact page is visible; new referrals are paused.':'The profile is a draft. Activate it when the partnership is ready.'}</p><label>Public referral and impact page<Input readOnly value={url(selected)} onFocus={e=>e.target.select()}/></label><div className="school-row-actions"><Button variant="outline" onClick={()=>copy(url(selected))}>Copy link</Button><a href={url(selected)} target="_blank" rel="noreferrer">Open page ↗</a></div><label className="school-message-label">Launch-message draft<Textarea readOnly rows={10} value={message}/></label><Button variant="outline" onClick={()=>copy(message)}>Copy draft</Button><p className="small">Nothing is sent automatically.</p></section>}
 {donation&&report&&<DonationEditor serverError={error} partners={report.partners.filter(p=>p.status!=='draft')} busy={busy} onCancel={()=>setDonation(false)} onSave={async value=>{const ok=await action('donations',value,'Completed donation recorded. Community totals are updated.');if(ok)setDonation(false);return ok;}}/>}
 <section className="panel"><h3>Donation records</h3><p className="small">Latest 100 transfers. Public totals include all completed records. Private references stay here. Correct an error by reversing the record, then recording the corrected transfer with a new reference.</p>{!report?.transfers.length?<p className="empty">No completed transfers recorded yet.</p>:<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Transfer date / reference</TableHead><TableHead>Transfer to Mia’s Place</TableHead><TableHead>Community allocations</TableHead><TableHead>Status</TableHead><TableHead>Correction</TableHead></TableRow></TableHeader><TableBody>{report.transfers.map(t=><TableRow key={t.id}><TableCell>{t.transferred_on}<span className="school-cell-detail">{t.reference}</span></TableCell><TableCell>{money(t.amount_cents)}</TableCell><TableCell>{t.allocations.map((a:any)=><div key={a.id}>{report.partners.find(p=>p.id===a.partner_id)?.name||'Community'}: {money(a.amount_cents)}</div>)}</TableCell><TableCell>{t.status}{t.reversal_reason&&<span className="school-cell-detail">{t.reversal_reason}</span>}</TableCell><TableCell>{t.status==='completed'&&<Button disabled={busy} variant="outline" onClick={()=>{setReversal(t);setReason('');}}>Correct record</Button>}</TableCell></TableRow>)}</TableBody></Table></div>}</section>
 <Dialog open={!!reversal} onOpenChange={open=>{if(!open&&!busy)setReversal(null);}}><DialogContent className="review-dialog"><DialogHeader><DialogTitle>Reverse this donation record?</DialogTitle><DialogDescription>This removes its allocations from public community totals and keeps the correction in your history. No money is moved.</DialogDescription></DialogHeader>{reversal&&<><p>{reversal.transferred_on} · {money(reversal.amount_cents)} · {reversal.reference}</p><label>Reason for correction<Textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} rows={3}/></label>{error&&<p className="message error" role="alert">{error}</p>}<div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={()=>setReversal(null)}>Keep record</Button><Button disabled={busy||!reason.trim()} onClick={async()=>{if(await action('donations/reverse',{id:reversal.id,reason},'Record reversed. Public totals reflect the correction.'))setReversal(null);}}>Reverse recorded allocations</Button></div></>}</DialogContent></Dialog>
 </div>;
}
function InfluencerEditor({partner,busy,onCancel,onSave}:{partner:Partner|null;busy:boolean;onCancel:()=>void;onSave:(v:any)=>Promise<void>}){
 const [id]=useState(()=>partner?.id||crypto.randomUUID()),[status,setStatus]=useState(partner?.status||'draft');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({id,revision:partner?.revision||0,code:partner?.code||String(f.get('code')),name:String(f.get('name')),intro:String(f.get('intro')),contactEmail:String(f.get('email')),status});}
 return <form className="panel" onSubmit={submit}><h3>{partner?'Edit influencer':'Add influencer'}</h3><div className="price-fields"><label>Public name<Input name="name" defaultValue={partner?.name} maxLength={140} required/></label><label>Permanent link code<Input name="code" defaultValue={partner?.code} readOnly={!!partner} pattern="[a-z0-9]+(-[a-z0-9]+)*" minLength={3} maxLength={60} placeholder="community-name" required/></label></div><label>Community introduction<Textarea name="intro" defaultValue={partner?.intro} maxLength={500} rows={3} required placeholder="What this community is coming together to support…"/></label><label>Contact email (private, optional)<Input name="email" type="email" defaultValue={partner?.contactEmail} maxLength={254}/></label><fieldset><legend>Profile status</legend><div className="school-row-actions">{['draft','active','paused'].map(s=><Button key={s} type="button" variant={status===s?'default':'outline'} aria-pressed={status===s} onClick={()=>setStatus(s)}>{s.charAt(0).toUpperCase()+s.slice(1)}</Button>)}</div></fieldset><p className="small">Draft hides the page. Active enables referral credit and public impact. Paused keeps donation history visible while stopping new referrals. Existing subscription attribution stays unchanged.</p><div className="school-row-actions"><Button disabled={busy}>Save influencer</Button><Button variant="outline" type="button" disabled={busy} onClick={onCancel}>Cancel</Button></div></form>;
}
function DonationEditor({partners,busy,onCancel,onSave,serverError}:{serverError:string;partners:Partner[];busy:boolean;onCancel:()=>void;onSave:(value:any)=>Promise<boolean>}){
 const [id]=useState(()=>crypto.randomUUID()),[rows,setRows]=useState([{key:crypto.randomUUID(),partnerId:'',amount:''}]),[confirmed,setConfirmed]=useState(false),[review,setReview]=useState<any>(null),[error,setError]=useState('');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const input=validateDonation({id,reference:String(f.get('reference')),transferredOn:String(f.get('date')),amountCents:Math.round(Number(f.get('amount'))*100),allocations:rows.map(r=>({partnerId:r.partnerId,amountCents:Math.round(Number(r.amount)*100)})),confirmed});setError('');setReview(input);}catch(e){setError(e instanceof Error?e.message:'Check the donation details.');}}
 return <section className="panel donation-editor"><h3>Record a completed donation</h3><p>Enter a transfer already made to Mia’s Place. Assign the reconciled shares attributable to influencer communities. Unallocated money is excluded from community totals.</p><form onSubmit={submit}><div className="price-fields"><label>Actual transfer date<Input name="date" type="date" max={new Date().toISOString().slice(0,10)} required/></label><label>Total transfer (USD)<Input name="amount" type="number" min="0.01" max="1000000" step="0.01" required/></label></div><label>Bank or charity confirmation reference (private)<Input name="reference" maxLength={180} required placeholder="Unique reference identifying the completed transfer"/></label><h4>Community shares</h4>{rows.map((row,index)=><div className="donation-allocation" key={row.key}><div><label id={'allocation-label-'+row.key}>Community {index+1}</label><Select value={row.partnerId} onValueChange={value=>setRows(rows.map(r=>r.key===row.key?{...r,partnerId:value}:r))}><SelectTrigger aria-labelledby={'allocation-label-'+row.key}><SelectValue placeholder="Choose community"/></SelectTrigger><SelectContent>{partners.map(p=><SelectItem key={p.id} value={p.id}>{p.name} · {p.code}</SelectItem>)}</SelectContent></Select></div><label>Share (USD)<Input type="number" min="0.01" max="1000000" step="0.01" value={row.amount} onChange={e=>setRows(rows.map(r=>r.key===row.key?{...r,amount:e.target.value}:r))} required/></label><Button variant="outline" type="button" disabled={rows.length===1} aria-label={'Remove community share '+(index+1)} onClick={()=>setRows(rows.filter(r=>r.key!==row.key))}>Remove</Button></div>)}<Button type="button" variant="outline" disabled={rows.length>=25||rows.length>=partners.length} onClick={()=>setRows([...rows,{key:crypto.randomUUID(),partnerId:'',amount:''}])}>Add community share</Button><label className="checkbox-label donation-confirm"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>I have confirmed this transfer was completed and reconciled these community shares. This transfer has not already been recorded.</label>{error&&<p className="message error" role="alert">{error}</p>}<div className="school-row-actions"><Button disabled={busy||!confirmed}>Review public totals</Button><Button type="button" variant="outline" disabled={busy} onClick={onCancel}>Cancel</Button></div></form>
 <Dialog open={!!review} onOpenChange={open=>{if(!open&&!busy)setReview(null);}}><DialogContent className="review-dialog"><DialogHeader><DialogTitle>Publish these donation amounts?</DialogTitle><DialogDescription>This records an existing transfer. Each listed amount will be added to that community’s public total.</DialogDescription></DialogHeader>{review&&<><p><strong>{money(review.amountCents)}</strong> to Mia’s Place on {review.transferredOn}</p><p className="small">Private reference: {review.reference}</p><div className="review-diff">{review.allocations.map((a:any)=><div key={a.partnerId}><strong>{partners.find(p=>p.id===a.partnerId)?.name}</strong><p>Current: {money(partners.find(p=>p.id===a.partnerId)?.donatedCents||0)}</p><p>Add: {money(a.amountCents)} → New total: {money((partners.find(p=>p.id===a.partnerId)?.donatedCents||0)+a.amountCents)}</p></div>)}</div><p className="small">Unallocated portion: {money(review.amountCents-review.allocations.reduce((sum:number,a:any)=>sum+a.amountCents,0))}</p>{(serverError||error)&&<p className="message error" role="alert">{serverError||error}</p>}<div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={()=>setReview(null)}>Edit details</Button><Button disabled={busy} onClick={async()=>{const ok=await onSave(review);if(ok)setReview(null);else setError('The record was not confirmed. Check the page message, then retry with these same details or close to edit.');}}>Record donation & update totals</Button></div></>}</DialogContent></Dialog>
 </section>;
}
