'use client';
import { useState, useEffect, useCallback, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
type Partner={id:string;code:string;name:string;program:string;contactEmail:string;status:string;revision:number;referralVisits:number;paidOrders:number;activeSubscriptions:number;grossPaidCents:number};
async function api(input?:unknown){const response=await fetch('/api/admin/schools',{method:input===undefined?'GET':'POST',headers:input===undefined?{}:{'Content-Type':'application/json'},body:input===undefined?undefined:JSON.stringify(input),cache:'no-store'});const value:any=await response.json();if(!response.ok)throw new Error(value.error||'Could not load School Partners.');return value;}
const dollars=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export default function SchoolPartners({onUpdated}:{onUpdated:()=>Promise<unknown>}){
 const [partners,setPartners]=useState<Partner[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Partner|null>(null),[adding,setAdding]=useState(false),[selected,setSelected]=useState<Partner|null>(null),[origin,setOrigin]=useState('');
 const refresh=useCallback(async()=>{const report=await api();setPartners(report.partners);setLoaded(true);return report;},[]);
 useEffect(()=>{setOrigin(window.location.origin);refresh().catch(e=>setError(e.message));},[refresh]);
 const link=(p:Partner)=>`${origin}/schools/${p.code}`;
 const message=selected?`A little treat can make a difference for ${selected.name}.\n\nOur district’s Sunnybunch School Partner link supports ${selected.program}. Sunnybunch donates all profits to Mia’s Place, which grants the district-attributed share to our program. Donations are based on profit after business costs, not the purchase price.\n\nUse our link: ${link(selected)}\n\nEligible purchases within 30 days of the most recent district link receive credit. Subscriptions keep their original district on renewals until cancellation. Selection is browser-specific; removing it affects future purchases, not existing subscriptions.\n\nLaunch draft only: checkout and subscriptions are not yet connected. Review program arrangements with Mia’s Place before sending this message.`:'';
 async function copy(value:string,what:string){try{await navigator.clipboard.writeText(value);setNotice(what+' copied.');setError('');}catch{setError('Clipboard access is unavailable. Select and copy the text instead.');}}
 async function save(value:any){setBusy(true);setError('');setNotice('');try{await api(value);await refresh();await onUpdated();setEditing(null);setAdding(false);setSelected(null);setNotice('District saved. Its link works only while its status is Active.');}catch(e){setError(e instanceof Error?e.message:'Could not save the district.');}finally{setBusy(false);}}
 function download(){const rows=[['District','Code','Program','Status','Referral visits','Paid orders','Gross paid USD (before refunds/costs)','Active subscriptions','Profit allocation','Grants transferred'],...partners.map(p=>[p.name,p.code,p.program,p.status,p.referralVisits,p.paidOrders,(p.grossPaidCents/100).toFixed(2),p.activeSubscriptions,'Pending reconciliation','Not connected'])];const cell=(v:unknown)=>{let s=String(v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const blob=new Blob([rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sunnybunch-school-partners.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="school-admin"><div className="section-top school-admin-top"><div><p className="eyebrow">SUNNYBUNCH × MIA’S PLACE</p><h2>School Partners</h2><p>District links, referral activity and the path from treats to opportunity.</p></div><div className="header-actions"><Button variant="outline" disabled={!loaded||busy} onClick={download}>Export report</Button><Button disabled={busy} onClick={()=>{setAdding(true);setEditing(null);setError('');}}>Add district</Button></div></div>
 {error&&<p className="message error" role="alert">{error}</p>}{notice&&<p className="message" role="status">{notice}</p>}
 <div className="overview-grid"><section className="panel sunshine"><h3>One donation commitment.</h3><p>All Sunnybunch profits go to Mia’s Place. Mia’s Place grants the share attributed to each district to that district’s designated special education program.</p><p className="small">The district share is part of the 100% commitment, not an additional donation.</p></section><section className="panel"><h3>Your attribution rules</h3><p>Most recent active district link · 30-day window · subscriptions retain their original district until cancellation.</p><p className="small">Referral visits include repeat visits and bots. They are not unique families or sales. No student information is collected.</p></section></div>
 <p className="message">Referral tracking is live. Paid orders and renewals need a connected checkout. Profit allocation and grant transfers need reconciliation and accounting; no donation amount is calculated from revenue alone.</p>
 {(adding||editing)&&<PartnerEditor key={editing?.id||'new'} partner={editing} busy={busy} onSave={save} onCancel={()=>{setEditing(null);setAdding(false);}}/>}
 <section className="panel"><h3>District report</h3><p className="small">All-time referral visits and recorded commerce totals. Gross payments may include shipping and tax and are before refunds and costs.</p>{!loaded?<p className="empty">Loading districts… <Button variant="outline" onClick={()=>refresh().catch(e=>setError(e.message))}>Retry</Button></p>:partners.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>District / program</TableHead><TableHead>Status</TableHead><TableHead>Visits</TableHead><TableHead>Paid orders</TableHead><TableHead>Gross payments</TableHead><TableHead>Active subscriptions</TableHead><TableHead>Profit / grants</TableHead><TableHead>Manage</TableHead></TableRow></TableHeader><TableBody>{partners.map(p=><TableRow key={p.id}><TableCell><strong>{p.name}</strong><span className="school-cell-detail">{p.program}</span><code>{p.code}</code></TableCell><TableCell>{p.status}</TableCell><TableCell>{p.referralVisits}</TableCell><TableCell>{p.paidOrders}</TableCell><TableCell>{dollars(p.grossPaidCents)}</TableCell><TableCell>{p.activeSubscriptions}</TableCell><TableCell>Pending<span className="school-cell-detail">Accounting not connected</span></TableCell><TableCell><div className="school-row-actions"><Button variant="outline" disabled={busy} onClick={()=>{setEditing(p);setAdding(false);setError('');}}>Edit</Button><Button variant="outline" onClick={()=>setSelected(p)}>Link & message</Button></div></TableCell></TableRow>)}</TableBody></Table></div>:<div className="empty"><h3>Your first district starts here.</h3><p>Add its name, designated program and a permanent link code. Save it as a draft until the partnership is ready.</p><Button onClick={()=>setAdding(true)}>Add first district</Button></div>}</section>
 {selected&&<section className="panel"><h3>{selected.name}: sharing kit</h3><p>{selected.status==='active'?'This link records referrals.':'This link is inactive. Set the district to Active when the partnership is ready.'}</p><label>District referral link<Input value={link(selected)} readOnly onFocus={e=>e.target.select()}/></label><div className="school-row-actions"><Button variant="outline" onClick={()=>copy(link(selected),'District link')}>Copy link</Button><a href={link(selected)} target="_blank" rel="noreferrer">Open partner page ↗</a></div><label className="school-message-label">Family launch-message draft<Textarea readOnly rows={12} value={message}/></label><Button variant="outline" onClick={()=>copy(message,'Launch-message draft')}>Copy message draft</Button><p className="small">Copying does not send a message. Messages are sent by the district through its own family communication channels.</p></section>}
 </div>;
}
function PartnerEditor({partner,busy,onSave,onCancel}:{partner:Partner|null;busy:boolean;onSave:(v:any)=>Promise<void>;onCancel:()=>void}){
 const [status,setStatus]=useState(partner?.status||'draft'),[id]=useState(()=>partner?.id||crypto.randomUUID());
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);onSave({id,revision:partner?.revision||0,code:partner?.code||String(form.get('code')),name:String(form.get('name')),program:String(form.get('program')),contactEmail:String(form.get('contactEmail')),status});}
 return <form className="panel school-editor" onSubmit={submit}><h3>{partner?'Edit district':'Add a school district'}</h3><div className="price-fields"><label>District name<Input name="name" defaultValue={partner?.name} maxLength={140} required/></label><label>Designated special education program<Input name="program" defaultValue={partner?.program} maxLength={200} required/></label></div><div className="price-fields"><label>Permanent link code<Input name="code" defaultValue={partner?.code} readOnly={!!partner} pattern="[a-z0-9]+(-[a-z0-9]+)*" minLength={3} maxLength={60} placeholder="district-name" required/><span className="school-cell-detail">Lowercase letters, numbers and hyphens. Cannot change after saving.</span></label><label>District contact email (private, optional)<Input name="contactEmail" type="email" defaultValue={partner?.contactEmail} maxLength={254}/></label></div><fieldset><legend>Partner status</legend><div className="school-row-actions">{['draft','active','paused'].map(value=><Button key={value} type="button" variant={status===value?'default':'outline'} aria-pressed={status===value} onClick={()=>setStatus(value)}>{value.charAt(0).toUpperCase()+value.slice(1)}</Button>)}</div></fieldset><p className="small">Activate after the district and Mia’s Place agree on the partnership. Pausing stops new referral credit; it preserves historical records and original subscription attribution.</p><div className="school-row-actions"><Button disabled={busy}>Save district</Button><Button type="button" disabled={busy} variant="outline" onClick={onCancel}>Cancel</Button></div></form>;
}
