'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { applyChanges, CONFIRMED_NUTRITION } from '@/lib/commerce.mjs';
import { MISSION_STATEMENT } from '@/lib/mission-copy.mjs';
import './studio.css';
import SchoolPartners from './schools';
import Influencers from './influencers';
type Product={id:string;name:string;description:string;image:string;priceCents:number;subscriptionPriceCents:number;published:boolean;stock:number|null};
type Store={initialized:boolean;revision:number;products:Product[];content:Record<string,string>;proposals:any[];audit:any[];movements:any[];orders:any[];subscriptions:any[];billing:{connected:boolean}};
const dollars=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const date=(value:string)=>new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
const labels:Record<string,string>={name:'Name',description:'Description',priceCents:'One-time price',subscriptionPriceCents:'Subscription price',published:'Published',announcement:'Announcement',heroDescription:'Homepage introduction',missionLead:'Mission heading',missionStatement:'Mission statement'};
async function api(path:string,input?:unknown){const response=await fetch('/api/admin/'+path,{method:input===undefined?'GET':'POST',headers:input===undefined?{}:{'Content-Type':'application/json'},body:input===undefined?undefined:JSON.stringify(input),credentials:'same-origin',cache:'no-store'});const data:any=await response.json();if(!response.ok)throw new Error(data.error||'The request could not be completed.');return data;}
function diff(store:Store,changes:any[]){const {next}=applyChanges(store,changes);const result:{label:string;before:string;after:string}[]=[];for(const p of next.products){const old=store.products.find(o=>o.id===p.id)!;for(const key of ['name','description','priceCents','subscriptionPriceCents','published','stock'] as const)if(p[key]!==old[key]){const format=(v:any)=>key.endsWith('Cents')?dollars(v):v===null?'Not configured':typeof v==='boolean'?(v?'Published':'Hidden'):String(v);result.push({label:`${old.name} · ${key==='stock'?'Stock (pouches)':labels[key]}`,before:format(old[key]),after:format(p[key])});}}for(const key of Object.keys(next.content))if(next.content[key]!==store.content[key])result.push({label:labels[key],before:store.content[key],after:next.content[key]});return result;}
export default function Studio({email}:{email:string}){
  const [store,setStore]=useState<Store|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview'),[review,setReview]=useState<any>(null),[aiJson,setAiJson]=useState('');
  const current=useRef<Store|null>(null);
  const refresh=useCallback(async()=>{const value=await api('snapshot');setStore(value);current.current=value;return value as Store;},[]);
  useEffect(()=>{refresh().catch(e=>setError(e.message));},[refresh]);
  useEffect(()=>{if(['#schools','#influencers'].includes(window.location.hash))setTab(window.location.hash.slice(1));},[]);
  const action=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setNotice('');try{await fn();await refresh();setNotice(message);return true;}catch(e){setError(e instanceof Error?e.message:'Could not save.');return false;}finally{setBusy(false);}};
  async function stage(changes:any[],summary:string,source='owner'){
    if(!store)return;
    const id=crypto.randomUUID();
    const ok=await action(()=>api('proposals',{id,baseRevision:store.revision,source,summary,changes}),'Change saved for review. Nothing is live until you apply it.');
    if(ok){setTab('review');setReview(current.current?.proposals.find(p=>p.id===id));}
  }
  useEffect(()=>{
    const context=(document as any).modelContext;if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const definitions=[
      {name:'read_influencer_impact',title:'Read Sunnybunch influencer report',description:'Read owner-only influencer referral metrics and recorded completed donation allocations. No payments, messages, profile changes or donation records are created.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('No input fields accepted.');return api('influencers');}},
      {name:'read_school_partners',title:'Read Sunnybunch School Partner report',description:'Read district referral visits, recorded sales and subscriptions, plus pending accounting status. Requires the signed-in owner. Does not send messages or change districts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('No input fields accepted.');return api('schools');}},
      {name:'read_sunnybunch_store',title:'Read Sunnybunch management brief',description:'Read the signed-in owner’s catalog, prices, inventory, site content, revision, and pending proposals. Does not change the store or expose payment credentials.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('No input fields accepted.');const s=await refresh();return {revision:s.revision,initialized:s.initialized,products:s.products,content:s.content,confirmedNutrition:CONFIRMED_NUTRITION,pendingProposals:s.proposals.filter(p=>p.status==='pending'),ordersCount:s.orders.length,subscriptionCount:s.subscriptions.length,checkoutAvailable:false};}},
      {name:'propose_sunnybunch_changes',title:'Propose Sunnybunch changes for owner review',description:'Stage product, stock or text changes for owner review. Does not apply changes, change billing, send messages, create orders or donate money. Get the current revision first. Inventory is measured in outer pouches. Owner must review and apply in the admin page.',inputSchema:{type:'object',properties:{id:{type:'string',description:'New UUID for this proposal; reuse on retry.'},baseRevision:{type:'integer',minimum:1},summary:{type:'string',maxLength:180},changes:{type:'array',minItems:1,maxItems:10,items:{oneOf:[{type:'object',properties:{type:{const:'update_product'},id:{enum:['raspberry','tropical']},patch:{type:'object',properties:{name:{type:'string'},description:{type:'string'},priceCents:{type:'integer',minimum:1,maximum:100000},subscriptionPriceCents:{type:'integer',minimum:1,maximum:100000},published:{type:'boolean'}},minProperties:1,additionalProperties:false}},required:['type','id','patch'],additionalProperties:false},{type:'object',properties:{type:{const:'set_inventory'},id:{enum:['raspberry','tropical']},quantity:{type:'integer',minimum:0,maximum:1000000},reason:{type:'string'}},required:['type','id','quantity','reason'],additionalProperties:false},{type:'object',properties:{type:{const:'adjust_inventory'},id:{enum:['raspberry','tropical']},delta:{type:'integer',minimum:-1000000,maximum:1000000},reason:{type:'string'}},required:['type','id','delta','reason'],additionalProperties:false},{type:'object',properties:{type:{const:'update_content'},patch:{type:'object',properties:{announcement:{type:'string'},heroDescription:{type:'string'},missionLead:{type:'string'},missionStatement:{type:'string'}},minProperties:1,additionalProperties:false}},required:['type','patch'],additionalProperties:false}]}}},required:['id','baseRevision','summary','changes'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>{const result=await api('proposals',{...input,source:'ai'});await refresh();setTab('review');setNotice('AI proposal ready for your review. No live changes made.');return {id:result.id,status:result.status,requiresOwnerReview:true};}}
    ];
    for(const definition of definitions){try{Promise.resolve(context.registerTool(definition,{signal:lifecycle.signal})).catch(()=>lifecycle.abort());}catch{lifecycle.abort();}}
    return()=>lifecycle.abort();
  },[refresh]);
  const brief=store?JSON.stringify({brand:'Sunnybunch',mission:MISSION_STATEMENT,confirmedNutrition:CONFIRMED_NUTRITION,ownerInstructions:'Propose changes only. All profits are committed to Mia’s Place. Use the confirmed 1 g total sugars amount with its 20 g sachet basis for both flavors. Do not invent other nutrition claims, comparative sugar claims, inventory, sales or donations.',revision:store.revision,products:store.products,content:store.content,influencerPartners:'No commission. Public community totals count completed donations recorded by the owner, not sales or estimated profit. One referral partner per purchase; school and influencer referrals share a 30-day last-link window. Existing subscriptions retain the original partner until cancellation.',schoolPartners:'Last active school or influencer link within 30 days. Subscriptions keep their original district until cancellation. All profits go to Mia’s Place, which grants each district-attributed share to its designated program. Paid sales and renewals await payment integration. Donation accounting is pending.',purchaseFormat:'25 × 20 g sachets per pouch; subscriptions every 30 days, shipping extra',allowedChanges:['update_product','set_inventory','adjust_inventory','update_content']},null,2):'';
  const pending=store?.proposals.filter(p=>p.status==='pending')||[];
  return <main className="studio">
    <header className="studio-header"><div><a href="/" className="studio-logo">Sunnybunch <span aria-hidden="true">☀</span></a><span className="studio-label">STORE STUDIO</span></div><div className="header-actions"><a href="/" target="_blank" rel="noreferrer">View store ↗</a><span>{email}</span><a href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a></div></header>
    <div className="studio-intro"><div><p className="eyebrow">A LITTLE ORDER BEHIND THE SUNSHINE</p><h1>Your store, at a glance.</h1><p>Manage the essentials. Give your AI assistant context. Review what goes live.</p></div><Button variant="outline" disabled={busy} onClick={()=>action(refresh,'Store refreshed.')}>Refresh</Button></div>
    {error&&<div className="message error" role="alert">{error}</div>}{notice&&<div className="message" role="status">{notice}</div>}
    {!store?<section className="panel"><h2>Loading your store</h2><p>If loading fails, use Refresh to try again.</p></section>:!store.initialized?<section className="panel setup"><p className="eyebrow">ONE-TIME SETUP</p><h2>Bring Sunnybunch into the studio.</h2><p>Save your two existing flavors, $30 one-time and $24.99 subscription prices, and approved mission copy to your store database. Inventory starts as unconfigured. No sales or customer records are created.</p><Button disabled={busy} onClick={()=>action(()=>api('initialize',{}),'Store initialized. Your catalog is ready to manage.')}>Initialize Sunnybunch</Button></section>:<>
    <div className="metric-grid"><div className="metric"><span>Catalog</span><strong>{store.products.filter(p=>p.published).length}<small> published flavors</small></strong></div><div className="metric"><span>Inventory</span><strong>{store.products.some(p=>p.stock===null)?'Set counts':store.products.reduce((n,p)=>n+(p.stock||0),0)}<small>{store.products.every(p=>p.stock!==null)?' pouches on hand':''}</small></strong></div><div className="metric"><span>Ready for review</span><strong>{pending.length}<small> proposals</small></strong></div><div className="metric warm"><span>Payments</span><strong>Not connected</strong><small>Checkout remains unavailable</small></div></div>
    <Tabs value={tab} onValueChange={setTab} className="studio-tabs"><TabsList className="studio-nav" aria-label="Store management">{[['overview','Overview'],['products','Products'],['inventory','Inventory'],['orders','Orders & subscriptions'],['schools','School Partners'],['influencers','Influencers & impact'],['content','Content'],['ai','AI workspace'],['review',`Review (${pending.length})`],['activity','Activity']].map(([id,label])=><TabsTrigger value={id} key={id}>{label}</TabsTrigger>)}</TabsList>
    <TabsContent value="schools"><SchoolPartners onUpdated={refresh}/></TabsContent>
    <TabsContent value="influencers"><Influencers onUpdated={refresh}/></TabsContent>
    <TabsContent value="overview"><div className="overview-grid"><section className="panel"><p className="eyebrow">YOUR NEXT STEPS</p><h2>Make it ready to sell.</h2><ol className="checklist"><li><strong>Catalog saved</strong><span>Two flavors, current prices and your mission are managed here.</span></li><li><strong>{store.products.every(p=>p.stock!==null)?'Inventory configured':'Set opening inventory'}</strong><span>Count finished outer pouches ready for sale.</span><Button variant="outline" onClick={()=>setTab('inventory')}>Manage stock</Button></li><li><strong>Connect payments and subscriptions</strong><span>Stripe setup, shipping rates and destinations, tax settings, and customer policies are still needed. This version does not charge customers.</span></li></ol></section><section className="panel sunshine"><p className="eyebrow">YOUR MISSION</p><h2>Little treats.<br/>Bigger possibilities.</h2><p>{store.content.missionStatement}</p><p className="small">A donation pledge is not a recorded donation. No donation amount or profit is calculated from sales alone.</p><Button variant="outline" onClick={()=>setTab('content')}>Edit store copy</Button></section></div></TabsContent>
    <TabsContent value="products"><div className="section-top"><div><h2>Your two flavors</h2><p>Prices are per 25-sachet pouch. Subscription deliveries repeat every 30 days.</p></div></div><div className="product-admin-grid">{store.products.map(product=><ProductEditor key={`${product.id}-${store.revision}`} product={product} disabled={busy} onSave={stage}/>)}</div></TabsContent>
    <TabsContent value="inventory"><section className="panel"><h2>Inventory, counted in pouches.</h2><p>Each pouch contains 25 sachets. Every approved change leaves a record with its reason.</p><div className="inventory-grid">{store.products.map(p=><form key={p.id} className="inventory-card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);stage([{type:'set_inventory',id:p.id,quantity:Number(f.get('quantity')),reason:String(f.get('reason'))}],`Set ${p.name} stock`);}}><h3>{p.name}</h3><strong className="stock-count">{p.stock===null?'Not configured':`${p.stock} pouches`}</strong><label>New on-hand count<Input name="quantity" type="number" min="0" max="1000000" step="1" required/></label><label>Reason for this count<Input name="reason" placeholder="Opening count, production run, recount…" maxLength={250} required/></label><Button disabled={busy}>Review stock change</Button></form>)}</div></section><section className="panel"><h2>Recent stock history</h2>{store.movements.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>When</TableHead><TableHead>Flavor</TableHead><TableHead>Before</TableHead><TableHead>After</TableHead><TableHead>Reason</TableHead></TableRow></TableHeader><TableBody>{store.movements.map(m=><TableRow key={m.id}><TableCell>{date(m.created_at)}</TableCell><TableCell>{store.products.find(p=>p.id===m.product_id)?.name}</TableCell><TableCell>{m.before_quantity??'Unconfigured'}</TableCell><TableCell>{m.after_quantity}</TableCell><TableCell>{m.reason}</TableCell></TableRow>)}</TableBody></Table></div>:<p className="empty">No stock movements yet.</p>}</section></TabsContent>
    <TabsContent value="orders"><section className="panel"><h2>Orders</h2><p>Payment status and fulfillment status are kept separately. Payments are not connected yet.</p>{store.orders.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Customer</TableHead><TableHead>Total</TableHead><TableHead>Payment</TableHead><TableHead>Fulfillment</TableHead></TableRow></TableHeader><TableBody>{store.orders.map(o=><TableRow key={o.id}><TableCell>{o.id}</TableCell><TableCell>{o.customer_email}</TableCell><TableCell>{dollars(o.total_cents)}</TableCell><TableCell>{o.payment_status}</TableCell><TableCell>{o.fulfillment_status}</TableCell></TableRow>)}</TableBody></Table></div>:<p className="empty">No orders have been created. Completed payments will need to be connected before paid orders appear here.</p>}</section><section className="panel"><h2>Subscriptions</h2><p>Per-pouch prices are managed in Products. Subscriptions bill every 30 days, plus shipping. Catalog edits do not change an existing billing agreement.</p>{store.subscriptions.length?store.subscriptions.map(s=><p key={s.id}>{s.customer_email} · {s.status}</p>):<p className="empty">No active billing agreements. Subscription enrollment, renewals and cancellation are not connected yet.</p>}</section></TabsContent>
    <TabsContent value="content"><section className="panel"><h2>The words behind the brand</h2><p>Approved changes appear on your storefront. These fields accept plain text.</p><form className="content-form" key={store.revision} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);stage([{type:'update_content',patch:Object.fromEntries(Object.keys(store.content).map(k=>[k,String(f.get(k))]))}],'Update storefront copy');}}>{Object.entries(store.content).map(([key,value])=><label key={key}>{labels[key]}<Textarea name={key} defaultValue={value} maxLength={key==='announcement'?120:500} required rows={key==='announcement'?2:3}/></label>)}<Button disabled={busy}>Review copy changes</Button></form></section></TabsContent>
    <TabsContent value="ai"><div className="overview-grid"><section className="panel"><p className="eyebrow">WORK WITH YOUR AI ASSISTANT</p><h2>Give it the full picture.</h2><p>Your assistant can read catalog and inventory information and draft product, stock or copy changes. Every proposal needs your review before it goes live.</p><div className="prompt-example">“Review my Sunnybunch catalog and suggest clearer product descriptions. Keep the facts and prices unchanged. Save your suggestions for my review.”</div><Button onClick={()=>navigator.clipboard.writeText(brief).then(()=>setNotice('Store brief copied. Paste it into your AI conversation.')).catch(()=>setError('Clipboard access is unavailable. Select and copy the brief below.'))}>Copy store brief</Button><details><summary>View the brief</summary><pre className="code-block">{brief}</pre></details><p className="small">Compatible browser assistants can use read_sunnybunch_store and propose_sunnybunch_changes while you’re signed in. This page does not have a separate AI chat service connected.</p></section><section className="panel"><h2>Bring back a proposal.</h2><p>Paste a structured proposal from your assistant. Saving it only adds it to your review queue.</p><form onSubmit={e=>{e.preventDefault();try{const value=JSON.parse(aiJson);if(!value||!Array.isArray(value.changes)||!value.summary)throw new Error('Include summary and changes.');stage(value.changes,String(value.summary),'ai');}catch(err){setError(err instanceof Error?err.message:'Invalid proposal.');}}}><label htmlFor="ai-proposal">Proposal JSON</label><Textarea id="ai-proposal" value={aiJson} onChange={e=>setAiJson(e.target.value)} rows={12} required placeholder={'{"summary":"Refine raspberry description","changes":[{"type":"update_product","id":"raspberry","patch":{"description":"Your proposed copy"}}]}'}/><Button disabled={busy}>Save for review</Button></form></section></div></TabsContent>
    <TabsContent value="review"><section className="panel"><h2>You decide what goes live.</h2><p>Check the exact changes. A proposal made against an older store revision must be recreated from current data.</p>{pending.length?pending.map(p=><div className="proposal-row" key={p.id}><div><span className="tag">{p.source==='ai'?'AI proposal':'Owner draft'}</span><h3>{p.summary}</h3><p>{date(p.created_at)} · {p.base_revision===store.revision?'Ready to review':'Store changed · needs a fresh proposal'}</p></div><Button variant="outline" onClick={()=>setReview(p)}>Review</Button></div>):<p className="empty">No changes awaiting review.</p>}</section></TabsContent>
    <TabsContent value="activity"><section className="panel"><h2>A record of your changes.</h2><p>Recent actions, with before-and-after data. Stock corrections create new entries.</p>{store.audit.map(a=><details key={a.id} className="audit-entry"><summary>{a.action.replaceAll('_',' ')} · {date(a.created_at)}</summary><p className="small">Actor: {a.actor}</p><pre className="code-block">{JSON.stringify({before:a.before,after:a.after},null,2)}</pre></details>)}</section></TabsContent>
    </Tabs></>}
    <Dialog open={!!review} onOpenChange={open=>{if(!open&&!busy)setReview(null);}}><DialogContent className="review-dialog"><DialogHeader><DialogTitle>Review this change</DialogTitle><DialogDescription>{review?.summary||'Review the proposed update before publishing.'}</DialogDescription></DialogHeader>{review&&store&&<>{error&&<p className="message error" role="alert">{error}</p>}<p className="small">{review.source==='ai'?'Proposed by AI':'Owner draft'} · Changes become live when you apply them.</p>{review.base_revision!==store.revision?<p className="message error">The store changed after this proposal. Reject it and create a new one using the current store data.</p>:<div className="review-diff">{diff(store,review.changes).map((d,i)=><div key={i}><strong>{d.label}</strong><p><span>Before</span>{d.before}</p><p><span>After</span>{d.after}</p></div>)}{review.changes.filter((c:any)=>c.reason).map((c:any,i:number)=><p key={i}><strong>Inventory reason:</strong> {c.reason}</p>)}</div>}<div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={async()=>{if(await action(()=>api(`proposals/${review.id}/reject`,{}),'Proposal rejected. No live changes made.'))setReview(null);}}>Reject</Button><Button disabled={busy||review.base_revision!==store.revision} onClick={async()=>{if(await action(()=>api(`proposals/${review.id}/apply`,{}),'Changes applied to your store.'))setReview(null);}}>Apply these changes</Button></div></>}</DialogContent></Dialog>
    <footer className="studio-footer">Sunnybunch Studio · Private owner workspace · <a href="/">Back to the store</a></footer>
  </main>;
}
function ProductEditor({product,disabled,onSave}:{product:Product;disabled:boolean;onSave:(changes:any[],summary:string)=>Promise<void>}){
  const [published,setPublished]=useState(product.published);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave([{type:'update_product',id:product.id,patch:{name:String(f.get('name')),description:String(f.get('description')),priceCents:Math.round(Number(f.get('price'))*100),subscriptionPriceCents:Math.round(Number(f.get('subscription'))*100),published}}],`Update ${product.name}`);}
  return <form className="panel product-editor" onSubmit={submit}><div className="product-editor-heading"><img src={product.image} width="100" height="100" alt={product.name+' packaging'}/><div><span className="tag">{product.id.toUpperCase()}</span><h3>{product.name}</h3><p>25 sachets · 500 g</p></div></div><label>Product name<Input name="name" defaultValue={product.name} maxLength={90} required/></label><label>Description<Textarea name="description" defaultValue={product.description} maxLength={400} rows={3} required/></label><div className="price-fields"><label>One-time price (USD)<Input name="price" type="number" min="0.01" max="1000" step="0.01" defaultValue={(product.priceCents/100).toFixed(2)} required/></label><label>Every 30 days (USD)<Input name="subscription" type="number" min="0.01" max="1000" step="0.01" defaultValue={(product.subscriptionPriceCents/100).toFixed(2)} required/></label></div><label className="checkbox-label"><Checkbox checked={published} onCheckedChange={value=>setPublished(value===true)}/>Published on the storefront</label><Button disabled={disabled}>Review product changes</Button></form>;
}
