import assert from 'node:assert/strict';
const origin='http://127.0.0.1:5173';
const get=path=>fetch(origin+path);
assert.equal((await get('/')).status,200);
assert.equal((await get('/api/catalog')).status,200);
assert.equal((await get('/api/admin/snapshot')).status,401);
assert.equal((await fetch(origin+'/api/admin/snapshot',{headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'seedy@sites.test'}})).status,401);
const login=await fetch(origin+'/signin-with-chatgpt?return_to=/admin',{redirect:'manual'});
const cookie=login.headers.get('set-cookie')?.split(';')[0];
assert.ok(cookie);
const request=(path,input,extra={})=>fetch(origin+path,{method:input===undefined?'GET':'POST',headers:{Cookie:cookie,...(input===undefined?{}:{Origin:origin,'Content-Type':'application/json'}),...extra},body:input===undefined?undefined:JSON.stringify(input)});
const initial=await request('/api/admin/initialize',{});assert.equal(initial.status,200,await initial.clone().text());
const store=await(await request('/api/admin/snapshot')).json();
assert.equal(store.initialized,true);
assert.equal((await request('/api/admin/proposals',{}, {Origin:'https://other.example'})).status,403);
assert.equal((await request('/api/admin/proposals',{changes:[{type:'delete_database'}]})).status,400);
const proposal={id:crypto.randomUUID(),baseRevision:store.revision,summary:'Local validation only',source:'owner',changes:[{type:'set_inventory',id:'raspberry',quantity:12,reason:'Local smoke validation'}]};
let response=await request('/api/admin/proposals',proposal);assert.equal(response.status,201,await response.clone().text());
response=await request(`/api/admin/proposals/${proposal.id}/apply`,{});assert.equal(response.status,200,await response.clone().text());
const after=await(await request('/api/admin/snapshot')).json();assert.equal(after.products.find(p=>p.id==='raspberry').stock,12);assert.ok(after.audit.length>=2);
const html=await(await request('/admin')).text();assert.ok(html.includes('Sunnybunch'));
console.log('HTTP smoke passed: public routes, anonymous/spoofed-header denial, owner sign-in, origin checks, proposal validation, persisted changes and admin rendering.');
