import { escapeSchoolText as escape } from './school-pages.mjs';
const money=cents=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const date=value=>new Date(value).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'});
export function influencerBanner(p){return `<aside class="school-support" aria-label="Community referral selection"><div><strong>Community Partner: ${escape(p.name)}</strong><span>Your eligible purchases help this community support Mia’s Place.</span></div><a href="/creators/${escape(p.code)}">See community impact</a><button type="button" data-clear-school>Remove</button><span data-school-status role="status"></span></aside>`;}
/** @param {any} impact */
export function influencerPage(impact=null,unavailable=false){
 const active=impact?.acceptingReferrals;
 const heading=impact?`${escape(impact.name)}’s community.<br><span>A little more good.</span>`:'Your community.<br><span>A little more good.</span>';
 const total=impact?`<section class="impact-total" id="impact" aria-labelledby="impact-heading"><div><p class="eyebrow">SMALL TREATS. SHARED IMPACT.</p><h2 id="impact-heading">Together, this community has helped donate</h2><strong class="impact-amount">${money(impact.donatedCents)}</strong><p class="impact-recipient">to Mia’s Place</p><p class="impact-source">${impact.donatedCents===0?'No completed donations recorded for this community yet.':'Completed donations recorded by Sunnybunch, attributed to this community.'}</p><p class="impact-updated">${impact.updatedAt?'Record updated '+date(impact.updatedAt)+'.':'The total updates when a completed donation is recorded.'}${impact.lastDonationOn?' Most recent donation: '+date(impact.lastDonationOn)+'.':''}</p><a class="text-link" href="/creators/${escape(impact.code)}?refresh=${Date.now()}#impact">Refresh total ↻</a></div><img src="/assets/sugar-sun-gummies.jpg" width="700" height="700" alt="Raspberry red and golden yellow sugar-coated gummy suns"></section>`:`<section class="creator-introduction"><img src="/assets/sugar-sun-gummies.jpg" width="700" height="700" alt="Red and golden yellow sugar-coated gummy suns"><div><p class="eyebrow">A COMMUNITY YOU CAN COUNT ON</p><h2>Share the sunshine.<br>See the difference.</h2><p>Every influencer partner gets a personal referral page with a public total of completed donations to Mia’s Place attributed to their community. Come back to see that impact grow.</p><p>No commissions. A shared purpose. All Sunnybunch profits are committed to Mia’s Place.</p></div></section>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${impact?escape(impact.name)+' · ':''}Community Impact · Sunnybunch</title><meta name="description" content="Share Sunnybunch, support Mia’s Place and see your community’s recorded donations."><link rel="icon" href="/assets/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;650;700&amp;family=Fredoka:wght@500;600;700&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/schools.css"><link rel="stylesheet" href="/creators.css"></head><body class="creator-page${impact?' has-community':''}"><a class="skip-link" href="#main">Skip to content</a><header class="schools-header"><a class="wordmark" href="/">Sunnybunch ☀</a><nav aria-label="Community navigation"><a href="/creators">Community Partners</a><a href="/#treats">Shop gummies ↗</a></nav></header><main id="main">
 ${unavailable?'<p class="school-alert" role="status">This community page is unavailable. Your existing referral selection has not changed.</p>':''}
 <section class="creator-hero"><p class="eyebrow">SUNNYBUNCH × MIA’S PLACE · COMMUNITY PARTNERS</p><h1>${heading}</h1><p class="creator-lead">${impact?escape(impact.intro):'Good candy brings people together. Let’s turn that togetherness into meaningful opportunity.'}</p><div class="creator-actions">${impact?`<a class="button button-dark" href="/#treats">${active?'Shop with this community':'Shop Sunnybunch'} ↗</a><a class="text-link" href="#impact">See our impact ↓</a>`:'<a class="button button-dark" href="#community-code">Find your community ↗</a><a class="text-link" href="/#purpose">Meet our mission</a>'}</div>${impact?`<p class="creator-selection">${active?'This visit selects '+escape(impact.name)+' for eligible purchases in this browser for 30 days.':'New referrals are paused for this community. Its donation history remains available, and your existing selection is unchanged.'}</p>`:''}</section>
 ${total}
 <section class="creator-explainer"><div><p class="eyebrow">WHAT THAT NUMBER MEANS</p><h2>Real donations.<br>More possibilities.</h2><p>The total is the share of completed Sunnybunch donations to Mia’s Place attributed to this community. Sunnybunch records a donation after confirming the transfer and reconciling the community’s share.</p><p>It counts money given, not sales, estimated profit or future pledges. Corrections to recorded donations are reflected in the total. These community shares are part of our existing commitment to donate 100% of profits.</p><p>Mia’s Place is our planned nonprofit, inspired by Mia and a future with meaningful paid employment, individualized support and lasting stability for people with autism and other disabilities.</p></div><div class="schools-faq"><h2>How your support adds up.</h2><details><summary>How does referral credit work?</summary><p>The most recent active school or influencer link you visit gets credit for eligible purchases within 30 days. Only one partner receives credit for a purchase. Cookies must be enabled, and the selection stays in this browser. You can remove it from the store’s referral banner.</p></details><details><summary>Do subscriptions keep supporting this community?</summary><p>Yes. The partner selected when a subscription starts stays with it on renewals until cancellation. Visiting another link does not change an existing subscription. A new subscription after cancellation uses the partner selected at that time.</p></details><details><summary>Does the influencer earn a commission?</summary><p>No. Influencers help their communities support Mia’s Place without a commission. Sunnybunch donates all profits to Mia’s Place, after business costs including production, shipping, payment fees, refunds and operating expenses.</p></details><details><summary>When will the total change?</summary><p>When Sunnybunch records a completed donation and this community’s reconciled share. Reload this page for the latest total. Purchases and profit do not immediately become donations. A regular donation schedule has not yet been set.</p></details><p class="creator-setup-note">Online checkout and subscription billing are not connected yet. The public total uses completed donations recorded by Sunnybunch; it is not connected to bank records automatically.</p></div></section>
 ${!impact?'<section class="schools-code" id="community-code"><h2>Find your community.</h2><p>Use your influencer’s link or enter their Sunnybunch code.</p><form action="/creators" method="get"><label for="creator-code">Community link code</label><div><input id="creator-code" name="code" minlength="3" maxlength="60" pattern="[A-Za-z0-9]+(-[A-Za-z0-9]+)*" required placeholder="Community code"><button type="submit" class="button button-dark">See community impact</button></div></form></section>':''}
 </main><footer><a class="wordmark" href="/">Sunnybunch ☀</a><p>Little treats. Bigger possibilities.</p><div class="footer-links"><a href="/#purpose">Our story</a><a href="/schools">School Partners</a><a href="/">Shop Sunnybunch</a></div></footer></body></html>`;
}
