export const escapeSchoolText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function schoolBanner(school){return school?`<aside class="school-support" aria-label="School Partner selection"><div><strong>School Partner: ${escapeSchoolText(school.name)}</strong><span>Eligible purchases support ${escapeSchoolText(school.program)} through Mia’s Place.</span></div><a href="/schools">How it works</a><button type="button" data-clear-school>Remove</button><span data-school-status role="status"></span></aside>`:'';}
/** @param {{name:string,program:string}|null} school */
export function schoolPage(school=null,unavailable=false){
 const heading=school?`A little sunshine for ${escapeSchoolText(school.name)}.`:'Little treats. More possibilities at school.';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${school?escapeSchoolText(school.name)+' · ':''}School Partners · Sunnybunch</title><meta name="description" content="Support school special education programs through Sunnybunch and Mia’s Place."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;650;700&amp;family=Fredoka:wght@500;600;700&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/schools.css"><script type="module" src="/school-referral.js"></script></head><body class="schools-page"><header class="schools-header"><a class="wordmark" href="/">Sunnybunch ☀</a><a href="/#treats">Shop the gummies ↗</a></header><main>
 ${unavailable?'<div class="school-alert" role="status">This district link is unavailable. Your previous referral selection has not been changed. Ask your district for its current link.</div>':''}
 <section class="schools-hero"><div><p class="eyebrow">SUNNYBUNCH × MIA’S PLACE · SCHOOL PARTNERS</p><h1>${heading}</h1><p class="schools-lead">${school?`Your selected program: <strong>${escapeSchoolText(school.program)}</strong>. Eligible Sunnybunch purchases help direct donations to this program through Mia’s Place.`:'A simple way for school communities to support their special education programs. Share the district’s link, enjoy your favorite sour gummy suns, and help create more opportunities.'}</p>${school?'<p class="school-selected">Your district is selected for the next 30 days on this browser.</p><a class="button button-dark" href="/#treats">Shop with your district selected ↗</a>':'<a class="button button-dark" href="#district-link">Use your district’s link code ↗</a>'}<p class="schools-small">Program setup is underway. Checkout is not connected yet, so no purchases, subscriptions or donations can be completed on this site.</p></div><img src="/assets/sugar-sun-gummies.jpg" alt="Red and golden yellow sugar-coated gummy suns" width="700" height="700"></section>
 <section class="schools-steps" aria-label="How School Partners works"><article><span>01</span><h2>Your district shares.</h2><p>A participating district shares its own Sunnybunch link with families. Your selection stays with this browser for 30 days.</p></article><article><span>02</span><h2>Your treats give back.</h2><p>Once checkout opens, eligible purchases count toward your district. A subscription keeps its original district on every renewal until that subscription is canceled.</p></article><article><span>03</span><h2>Possibilities grow.</h2><p>Sunnybunch donates all profits to Mia’s Place. Mia’s Place grants the share attributable to your district to its designated special education program.</p></article></section>
 <section class="schools-details"><div><p class="eyebrow">ONE MISSION. A COMMUNITY OF SUPPORT.</p><h2>Good things happen when we show up together.</h2><p>Mia’s Place is our planned nonprofit, inspired by Mia and a vision of meaningful paid work, individualized support and lasting stability for people with autism and other disabilities. School Partners extends that purpose into school communities.</p><p>Donations are based on profit after business costs, including product costs, shipping, payment fees, refunds and allocated operating expenses. Sales totals are not donation totals. Grant amounts are confirmed after reconciliation; a transfer schedule has not yet been set.</p><a class="text-link" href="/#purpose">Meet the mission ↗</a></div><div class="schools-faq"><h2>The details, simply.</h2><details><summary>Which district receives credit?</summary><p>The most recent active school or influencer link you visit receives credit for eligible purchases made within 30 days. A new partner link restarts that window. Each purchase credits only one partner. Cookies must be enabled; the selection does not move between devices or browsers.</p></details><details><summary>What about subscriptions?</summary><p>The district selected when the subscription begins stays with that subscription until cancellation, even after the 30-day browser window ends. Visiting another partner link does not move an existing subscription. A new subscription after cancellation uses the selection in effect when it begins.</p></details><details><summary>Can I change or remove my selection?</summary><p>Visit another active school or influencer link to change future purchase credit, or use Remove in the store’s School Partner banner. Removing the selection does not change an existing subscription. Paused district links cannot receive new purchase or subscription referrals.</p></details><details><summary>What information is collected?</summary><p>The referral system stores a random browser token, the district and expiration date. It does not ask for a student’s name, disability, diagnosis or school records. District contact information and store reports are private to the store owner.</p></details></div></section>
 <section class="schools-code" id="district-link"><h2>Have a district code?</h2><p>Enter the code supplied by your district, or use its full link. Participating districts are added by the Sunnybunch team.</p><form action="/schools" method="get"><label for="school-code">District link code</label><div><input id="school-code" name="code" minlength="3" maxlength="60" pattern="[A-Za-z0-9]+(-[A-Za-z0-9]+)*" placeholder="Your district’s code" required><button class="button button-dark" type="submit">Select district</button></div></form></section>
 </main><footer><a class="wordmark" href="/">Sunnybunch ☀</a><p>Little treats. Bigger possibilities.</p><a href="/">Back to the store</a></footer></body></html>`;
}
